const stores = [
  {
    id: 1,
    name: "Fruit Salad",
    description:
      "Fruit Salad is a grocery store that offers fresh fruits and vegetables.",
    image: require("@/assets/stores/fruit-salad.png"),
    delivery: 30,
    distance: 1.2,
    categories: ["Groceries", "Produce"],
  },
  {
    id: 2,
    name: "Shaq Bread",
    description:
      "Shaq Bread is a grocery store that offers fresh bread and pastries.",
    image: require("@/assets/stores/shaq-bread.png"),
    delivery: 25,
    distance: 1.5,
    categories: ["Groceries", "Produce"],
  },
  {
    id: 3,
    name: "Imperio Fresh",
    description:
      "Imperio Fresh is a grocery store that offers fresh produce and seafood.",
    image: require("@/assets/stores/imperio-fresh.png"),
    delivery: 20,
    distance: 1.8,
    categories: ["Groceries", "Produce"],
  },
  {
    id: 4,
    name: "Borcelle Medical",
    description:
      "Borcelle Medical is a grocery store that offers medical supplies and equipment.",
    image: require("@/assets/stores/borcelle-medical.png"),
    delivery: 35,
    distance: 2.1,
    categories: [""],
  },
  {
    id: 5,
    name: "Jiwaw Dairy",
    description:
      "Jiwaw Dairy is a grocery store that offers fresh dairy products.",
    image: require("@/assets/stores/jiwaw-dairy.png"),
    delivery: 40,
    distance: 2.4,
    categories: ["Groceries", "Produce"],
  },
  {
    id: 6,
    name: "Fresh Shrimp",
    description: "Fresh Shrimp is a grocery store that offers fresh seafood.",
    image: require("@/assets/stores/fresh-shrimp.png"),
    delivery: 45,
    distance: 2.7,
    categories: ["Seafood"],
  },
  {
    id: 7,
    name: "Larana Inc.",
    description:
      "Larana Inc. is a grocery store that offers fresh produce and groceries.",
    image: require("@/assets/stores/larana-inc.png"),
    delivery: 50,
    distance: 3.0,
    categories: ["Groceries", "Produce"],
  },
  {
    id: 8,
    name: "Fresh Drinks",
    description:
      "Fresh Drinks is a grocery store that offers fresh drinks and beverages.",
    image: require("@/assets/stores/fresh-drinks.png"),
    delivery: 55,
    distance: 3.3,
    categories: ["Groceries"],
  },
  {
    id: 9,
    name: "Delicious Snacks",
    description:
      "Delicious Snacks is a grocery store that offers delicious snacks and treats.",
    image: require("@/assets/stores/delicious-snacks.png"),
    delivery: 60,
    distance: 3.6,
    categories: ["Groceries"],
  },
  {
    id: 10,
    name: "Fine Wine",
    description:
      "Fine Wine is a grocery store that offers fine wine and spirits.",
    image: require("@/assets/stores/fine-wine.png"),
    delivery: 65,
    distance: 3.9,
    categories: ["Alcohol"],
  },
];

const categories = [
  {
    id: 1,
    name: "Groceries",
    icon: "shopping_basket",
    link: "/(root)/category",
  },
  {
    id: 2,
    name: "Produce",
    icon: "carrots",
    link: "/(root)/category",
  },
  {
    id: 3,
    name: "Seafood",
    icon: "fish_bone",
    link: "/(root)/category",
  },
  {
    id: 4,
    name: "Alcohol",
    icon: "drink",
    link: "/(root)/category",
  },
];

const products = [
  {
    id: 1,
    name: "Bistec Pulpa Blanca",
    description:
      "Bistec Pulpa Blanca es un corte de carne de res muy suave y jugoso.",
    price: 157.0,
    images: [
      require("@/assets/products/bistec-pulpa-blanca.png"),
      require("@/assets/products/bistec-pulpa-blanca.png"),
      require("@/assets/products/bistec-pulpa-blanca.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Best Sellers", "Seafood & Plant-Based"],
    featured: true,
    type: "groceries",
    store_id: 3,
  },
  {
    id: 2,
    name: "Arroz Súper",
    description:
      "Arroz Súper es un arroz de grano largo y fino que se cocina fácilmente.",
    price: 36.9,
    images: [
      require("@/assets/products/arroz-super.png"),
      require("@/assets/products/arroz-super.png"),
      require("@/assets/products/arroz-super.png"),
    ],
    quantity: 15,
    unit: "900 g",
    categories: ["Best Sellers", "Rice"],
    featured: true,
    store_id: 3,
  },
  {
    id: 3,
    name: "Jitomate Huaje",
    description: "Jitomate Huaje es un jitomate de gran tamaño y sabor dulce.",
    price: 44.9,
    images: [
      require("@/assets/products/jitomate-huaje.png"),
      require("@/assets/products/jitomate-huaje.png"),
      require("@/assets/products/jitomate-huaje.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Best Sellers", "Fruits & Vegetables"],
    featured: true,
    store_id: 1,
  },
  {
    id: 4,
    name: "Plátano",
    description: "Plátano es una fruta dulce y rica en potasio.",
    price: 32.9,
    images: [
      require("@/assets/products/platano.png"),
      require("@/assets/products/platano.png"),
      require("@/assets/products/platano.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Best Sellers", "Fruits & Vegetables"],
    featured: true,
    store_id: 1,
  },
  {
    id: 5,
    name: "Aceite Vegetal",
    description:
      "Aceite Vegetal es un aceite de cocina que se utiliza para freír y cocinar.",
    price: 42.9,
    images: [
      require("@/assets/products/aceite-vegetal.png"),
      require("@/assets/products/aceite-vegetal.png"),
      require("@/assets/products/aceite-vegetal.png"),
    ],
    quantity: 10,
    unit: "1 L",
    categories: ["Best Sellers", "Oil"],
    featured: true,
    store_id: 3,
  },
  {
    id: 6,
    name: "Papel Higiénico",
    description:
      "Papel Higiénico es un papel suave y absorbente que se utiliza para limpiar.",
    price: 158.0,
    images: [
      require("@/assets/products/papel-higinieco.png"),
      require("@/assets/products/papel-higinieco.png"),
      require("@/assets/products/papel-higinieco.png"),
    ],
    quantity: 10,
    unit: "10 Rolls",
    categories: ["Best Sellers", "Paper"],
    featured: true,
    store_id: 3,
  },
  {
    id: 7,
    name: "Cebolla Blanca",
    description: "Cebolla Blanca es una cebolla de gran tamaño y sabor fuerte.",
    price: 39.5,
    images: [
      require("@/assets/products/cebolla-blanca.png"),
      require("@/assets/products/cebolla-blanca.png"),
      require("@/assets/products/cebolla-blanca.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Best Sellers", "Fruits & Vegetables"],
    featured: true,
    store_id: 1,
  },
  {
    id: 8,
    name: "Zanahoria",
    description: "Zanahoria es una zanahoria de gran tamaño y sabor dulce.",
    price: 19.0,
    images: [
      require("@/assets/products/zanahoria.png"),
      require("@/assets/products/zanahoria.png"),
      require("@/assets/products/zanahoria.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Best Sellers", "Fruits & Vegetables"],
    featured: true,
    store_id: 1,
  },
  {
    id: 9,
    name: "Limón sin Semilla",
    description: "Limón sin Semilla es un limón de gran tamaño y sabor ácido.",
    price: 34.9,
    images: [
      require("@/assets/products/limon-sin-semilla.png"),
      require("@/assets/products/limon-sin-semilla.png"),
      require("@/assets/products/limon-sin-semilla.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Fruits & Vegetables"],
    featured: true,
    store_id: 1,
  },
  {
    id: 10,
    name: "Filete de Tilapia",
    description: "Filete de Tilapia es un filete de pescado blanco y suave.",
    price: 122.9,
    images: [
      require("@/assets/products/filete-de-tilapia.png"),
      require("@/assets/products/filete-de-tilapia.png"),
      require("@/assets/products/filete-de-tilapia.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Seafood & Plant-Based"],
    featured: true,
    store_id: 3,
  },
  {
    id: 11,
    name: "Pescado Sierra Madre",
    description: "Pescado Sierra Madre es un pescado de mar y sabor suave.",
    price: 186.4,
    images: [
      require("@/assets/products/pescado-sierra-madre.png"),
      require("@/assets/products/pescado-sierra-madre.png"),
      require("@/assets/products/pescado-sierra-madre.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Seafood & Plant-Based"],
    featured: true,
    store_id: 3,
  },
  {
    id: 12,
    name: "Pescado Lenguado",
    description: "Pescado Lenguado es un pescado de mar y sabor suave.",
    price: 319.2,
    images: [
      require("@/assets/products/pescado-lenguado.png"),
      require("@/assets/products/pescado-lenguado.png"),
      require("@/assets/products/pescado-lenguado.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Seafood & Plant-Based"],
    featured: true,
    store_id: 3,
  },
  {
    id: 13,
    name: "Codillo Chamorro",
    description: "Codillo Chamorro es un codillo de cerdo y sabor suave.",
    price: 77.0,
    images: [
      require("@/assets/products/codillo-chamorro.png"),
      require("@/assets/products/codillo-chamorro.png"),
      require("@/assets/products/codillo-chamorro.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Seafood & Plant-Based"],
    featured: true,
    store_id: 3,
  },
  {
    id: 14,
    name: "Huevo Blanco",
    description: "Huevo Blanco es un huevo de gallina y sabor suave.",
    price: 88.9,
    images: [
      require("@/assets/products/huevo-blanco.png"),
      require("@/assets/products/huevo-blanco.png"),
      require("@/assets/products/huevo-blanco.png"),
    ],
    quantity: 10,
    unit: "30 Eggs",
    categories: ["Dairy & Eggs"],
    featured: true,
    store_id: 3,
  },
  {
    id: 15,
    name: "Leche Pronto",
    description: "Leche Pronto es una leche de vaca y sabor suave.",
    price: 25.9,
    images: [
      require("@/assets/products/leche-pronto.png"),
      require("@/assets/products/leche-pronto.png"),
      require("@/assets/products/leche-pronto.png"),
    ],
    quantity: 10,
    unit: "380 ml",
    categories: ["Dairy & Eggs"],
    featured: true,
    store_id: 3,
  },
  {
    id: 16,
    name: "Leche Alpura",
    description: "Leche Alpura es una leche de vaca y sabor suave.",
    price: 101.0,
    images: [
      require("@/assets/products/leche-alpura.png"),
      require("@/assets/products/leche-alpura.png"),
      require("@/assets/products/leche-alpura.png"),
    ],
    quantity: 10,
    unit: "1L c/u",
    categories: ["Dairy & Eggs"],
    featured: true,
    store_id: 3,
  },
  {
    id: 17,
    name: "Huevo San Juan",
    description: "Huevo San Juan es un huevo de gallina y sabor suave.",
    price: 39.0,
    images: [
      require("@/assets/products/huevo-san-juan.png"),
      require("@/assets/products/huevo-san-juan.png"),
      require("@/assets/products/huevo-san-juan.png"),
    ],
    quantity: 10,
    unit: "12 Eggs",
    categories: ["Dairy & Eggs"],
    featured: true,
    store_id: 3,
  },
  {
    id: 18,
    name: "Leche Lala",
    description: "Leche Lala es una leche de vaca y sabor suave.",
    price: 144.0,
    images: [
      require("@/assets/products/leche-lala.png"),
      require("@/assets/products/leche-lala.png"),
      require("@/assets/products/leche-lala.png"),
    ],
    quantity: 10,
    unit: "1 L",
    categories: ["Dairy & Eggs"],
    featured: true,
    store_id: 3,
  },
  {
    id: 19,
    name: "Queso Crema",
    description: "Queso Crema es un queso de vaca y sabor suave.",
    price: 47.5,
    images: [
      require("@/assets/products/queso-crema.png"),
      require("@/assets/products/queso-crema.png"),
      require("@/assets/products/queso-crema.png"),
    ],
    quantity: 10,
    unit: "200 g",
    categories: ["Cheeses"],
    featured: true,
    store_id: 3,
  },
  {
    id: 20,
    name: "Queso Rebanado",
    description: "Queso Rebanado es un queso de vaca y sabor suave.",
    price: 93.5,
    images: [
      require("@/assets/products/queso-rebanado-400g.png"),
      require("@/assets/products/queso-rebanado-400g.png"),
      require("@/assets/products/queso-rebanado-400g.png"),
    ],
    quantity: 10,
    unit: "400 g",
    categories: ["Cheeses"],
    featured: true,
    store_id: 3,
  },
  {
    id: 21,
    name: "Queso Rebanado",
    description: "Queso Rebanado es un queso de vaca y sabor suave.",
    price: 53.0,
    images: [
      require("@/assets/products/queso-rebanado-200g.png"),
      require("@/assets/products/queso-rebanado-200g.png"),
      require("@/assets/products/queso-rebanado-200g.png"),
    ],
    quantity: 10,
    unit: "200 g",
    categories: ["Cheeses"],
    featured: true,
    store_id: 3,
  },
  {
    id: 22,
    name: "Queso Panela",
    description: "Queso Panela es un queso de vaca y sabor suave.",
    price: 79.0,
    images: [
      require("@/assets/products/queso-panela.png"),
      require("@/assets/products/queso-panela.png"),
      require("@/assets/products/queso-panela.png"),
    ],
    quantity: 10,
    unit: "400 g",
    categories: ["Cheeses"],
    featured: true,
    store_id: 3,
  },
  {
    id: 23,
    name: "Queso Crema Light",
    description: "Queso Crema Light es un queso de vaca y sabor suave.",
    price: 36.65,
    images: [
      require("@/assets/products/queso-crema-light.png"),
      require("@/assets/products/queso-crema-light.png"),
      require("@/assets/products/queso-crema-light.png"),
    ],
    quantity: 10,
    unit: "150 g",
    categories: ["Cheeses"],
    featured: true,
    store_id: 3,
  },
  {
    id: 24,
    name: "Pollo Entero",
    description: "Pollo Entero es un pollo y sabor suave.",
    price: 51.0,
    images: [
      require("@/assets/products/pollo-entero.png"),
      require("@/assets/products/pollo-entero.png"),
      require("@/assets/products/pollo-entero.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Birds"],
    featured: true,
    store_id: 3,
  },
  {
    id: 25,
    name: "Pechuga de Pollo",
    description: "Pechuga de Pollo es un pollo y sabor suave.",
    price: 99.9,
    images: [
      require("@/assets/products/pechuga-de-pollo.png"),
      require("@/assets/products/pechuga-de-pollo.png"),
      require("@/assets/products/pechuga-de-pollo.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Birds"],
    featured: true,
    store_id: 3,
  },
  {
    id: 26,
    name: "Pechuga sin Hueso",
    description: "Pechuga sin Hueso es un pollo y sabor suave.",
    price: 154.0,
    images: [
      require("@/assets/products/pechuga-sin-hueso.png"),
      require("@/assets/products/pechuga-sin-hueso.png"),
      require("@/assets/products/pechuga-sin-hueso.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Birds"],
    featured: true,
    store_id: 3,
  },
  {
    id: 27,
    name: "Pierna y Muslo",
    description: "Pierna y Muslo es un pollo y sabor suave.",
    price: 44.9,
    images: [
      require("@/assets/products/pierna-y-muslo.png"),
      require("@/assets/products/pierna-y-muslo.png"),
      require("@/assets/products/pierna-y-muslo.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Birds"],
    featured: true,
    store_id: 3,
  },
  {
    id: 28,
    name: "Milanesa Pollo",
    description: "Milanesa Pollo es un pollo y sabor suave.",
    price: 174.0,
    images: [
      require("@/assets/products/milanesa-pollo.png"),
      require("@/assets/products/milanesa-pollo.png"),
      require("@/assets/products/milanesa-pollo.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Birds"],
    featured: true,
    store_id: 3,
  },
  {
    id: 29,
    name: "Jamón de Pavo",
    description: "Jamón de Pavo es un jamón y sabor suave.",
    price: 59.0,
    images: [
      require("@/assets/products/jamon-de-pavo.png"),
      require("@/assets/products/jamon-de-pavo.png"),
      require("@/assets/products/jamon-de-pavo.png"),
    ],
    quantity: 10,
    unit: "450 g",
    categories: ["Ham & Sausage"],
    featured: true,
    store_id: 3,
  },
  {
    id: 30,
    name: "Pechuga de Pavo",
    description: "Pechuga de Pavo es un jamón y sabor suave.",
    price: 48.85,
    images: [
      require("@/assets/products/pechuga-de-pavo.png"),
      require("@/assets/products/pechuga-de-pavo.png"),
      require("@/assets/products/pechuga-de-pavo.png"),
    ],
    quantity: 10,
    unit: "250 g",
    categories: ["Ham & Sausage"],
    featured: true,
    store_id: 3,
  },
  {
    id: 31,
    name: "Jamón de Pierna",
    description: "Jamón de Pierna es un jamón y sabor suave.",
    price: 120.0,
    images: [
      require("@/assets/products/jamon-de-pierna.png"),
      require("@/assets/products/jamon-de-pierna.png"),
      require("@/assets/products/jamon-de-pierna.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Ham & Sausage"],
    featured: true,
    store_id: 3,
  },
  {
    id: 32,
    name: "Salchicha Alpino",
    description: "Salchicha Alpino es un jamón y sabor suave.",
    price: 33.8,
    images: [
      require("@/assets/products/salchicha-alpino.png"),
      require("@/assets/products/salchicha-alpino.png"),
      require("@/assets/products/salchicha-alpino.png"),
    ],
    quantity: 10,
    unit: "500 g",
    categories: ["Ham & Sausage"],
    featured: true,
    store_id: 3,
  },
  {
    id: 33,
    name: "Tocino Fud Ahumado",
    description: "Tocino Fud Ahumado es un jamón y sabor suave.",
    price: 69.5,
    images: [
      require("@/assets/products/tocino-fud-ahumado.png"),
      require("@/assets/products/tocino-fud-ahumado.png"),
      require("@/assets/products/tocino-fud-ahumado.png"),
    ],
    quantity: 10,
    unit: "250 g",
    categories: ["Ham & Sausage"],
    featured: true,
    store_id: 3,
  },
];

export default { stores, categories, products };
