const stores = [
  {
    id: 1,
    name: "Фруктовый салат",
    description:
      "Фруктовый салат - это продуктовый магазин, предлагающий свежие фрукты и овощи.",
    image: require("@/assets/stores/fruit-salad.png"),
    delivery: 30,
    distance: 1.2,
    categories: ["Продукты", "Овощи и фрукты"],
  },
  {
    id: 2,
    name: "Хлеб Шак",
    description:
      "Хлеб Шак - это продуктовый магазин, предлагающий свежий хлеб и выпечку.",
    image: require("@/assets/stores/shaq-bread.png"),
    delivery: 25,
    distance: 1.5,
    categories: ["Продукты", "Овощи и фрукты"],
  },
  {
    id: 3,
    name: "Империо Фреш",
    description:
      "Империо Фреш - это продуктовый магазин, предлагающий свежие продукты и морепродукты.",
    image: require("@/assets/stores/imperio-fresh.png"),
    delivery: 20,
    distance: 1.8,
    categories: ["Продукты", "Овощи и фрукты"],
  },
  {
    id: 4,
    name: "Борселл Медикал",
    description:
      "Борселл Медикал - это продуктовый магазин, предлагающий медицинские принадлежности и оборудование.",
    image: require("@/assets/stores/borcelle-medical.png"),
    delivery: 35,
    distance: 2.1,
    categories: [""],
  },
  {
    id: 5,
    name: "Дживау Молочные",
    description:
      "Дживау Молочные - это продуктовый магазин, предлагающий свежие молочные продукты.",
    image: require("@/assets/stores/jiwaw-dairy.png"),
    delivery: 40,
    distance: 2.4,
    categories: ["Продукты", "Овощи и фрукты"],
  },
  {
    id: 6,
    name: "Свежие креветки",
    description: "Свежие креветки - это продуктовый магазин, предлагающий свежие морепродукты.",
    image: require("@/assets/stores/fresh-shrimp.png"),
    delivery: 45,
    distance: 2.7,
    categories: ["Морепродукты"],
  },
  {
    id: 7,
    name: "Ларана Инк.",
    description:
      "Ларана Инк. - это продуктовый магазин, предлагающий свежие продукты и бакалею.",
    image: require("@/assets/stores/larana-inc.png"),
    delivery: 50,
    distance: 3.0,
    categories: ["Продукты", "Овощи и фрукты"],
  },
  {
    id: 8,
    name: "Свежие напитки",
    description:
      "Свежие напитки - это продуктовый магазин, предлагающий свежие напитки и безалкогольные коктейли.",
    image: require("@/assets/stores/fresh-drinks.png"),
    delivery: 55,
    distance: 3.3,
    categories: ["Продукты"],
  },
  {
    id: 9,
    name: "Вкусные закуски",
    description:
      "Вкусные закуски - это продуктовый магазин, предлагающий вкусные закуски и лакомства.",
    image: require("@/assets/stores/delicious-snacks.png"),
    delivery: 60,
    distance: 3.6,
    categories: ["Продукты"],
  },
  {
    id: 10,
    name: "Прекрасное вино",
    description:
      "Прекрасное вино - это продуктовый магазин, предлагающий прекрасные вина и спиртные напитки.",
    image: require("@/assets/stores/fine-wine.png"),
    delivery: 65,
    distance: 3.9,
    categories: ["Алкоголь"],
  },
];

const categories = [
  {
    id: 1,
    name: "Продукты",
    icon: "shopping_basket",
    link: "/(root)/category",
  },
  {
    id: 2,
    name: "Овощи и фрукты",
    icon: "carrots",
    link: "/(root)/category",
  },
  {
    id: 3,
    name: "Морепродукты",
    icon: "fish_bone",
    link: "/(root)/category",
  },
  {
    id: 4,
    name: "Алкоголь",
    icon: "drink",
    link: "/(root)/category",
  },
];

const products = [
  {
    id: 1,
    name: "Бифштекс Пульпа Бланка",
    description:
      "Бифштекс Пульпа Бланка - это очень нежный и сочный кусок говядины.",
    price: 157.0,
    images: [
      require("@/assets/products/bistec-pulpa-blanca.png"),
      require("@/assets/products/bistec-pulpa-blanca.png"),
      require("@/assets/products/bistec-pulpa-blanca.png"),
    ],
    quantity: 10,
    unit: "1 кг",
    categories: ["Хиты продаж", "Морепродукты и растительные"],
    featured: true,
    type: "groceries",
    store_id: 3,
  },
  {
    id: 2,
    name: "Рис Супер",
    description:
      "Рис Супер - это длиннозерный и тонкий рис, который легко готовится.",
    price: 36.9,
    images: [
      require("@/assets/products/arroz-super.png"),
      require("@/assets/products/arroz-super.png"),
      require("@/assets/products/arroz-super.png"),
    ],
    quantity: 15,
    unit: "900 г",
    categories: ["Хиты продаж", "Рис"],
    featured: true,
    store_id: 3,
  },
  {
    id: 3,
    name: "Помидор Хуахе",
    description: "Помидор Хуахе - это помидор большого размера со сладким вкусом.",
    price: 44.9,
    images: [
      require("@/assets/products/jitomate-huaje.png"),
      require("@/assets/products/jitomate-huaje.png"),
      require("@/assets/products/jitomate-huaje.png"),
    ],
    quantity: 10,
    unit: "1 кг",
    categories: ["Хиты продаж", "Овощи и фрукты"],
    featured: true,
    store_id: 1,
  },
  {
    id: 4,
    name: "Банан",
    description: "Банан - это сладкий фрукт, богатый калием.",
    price: 32.9,
    images: [
      require("@/assets/products/platano.png"),
      require("@/assets/products/platano.png"),
      require("@/assets/products/platano.png"),
    ],
    quantity: 10,
    unit: "1 кг",
    categories: ["Хиты продаж", "Овощи и фрукты"],
    featured: true,
    store_id: 1,
  },
  {
    id: 5,
    name: "Растительное масло",
    description:
      "Растительное масло - это кулинарное масло, используемое для жарки и приготовления пищи.",
    price: 42.9,
    images: [
      require("@/assets/products/aceite-vegetal.png"),
      require("@/assets/products/aceite-vegetal.png"),
      require("@/assets/products/aceite-vegetal.png"),
    ],
    quantity: 10,
    unit: "1 л",
    categories: ["Хиты продаж", "Масла"],
    featured: true,
    store_id: 3,
  },
  {
    id: 6,
    name: "Туалетная бумага",
    description:
      "Туалетная бумага - это мягкая и впитывающая бумага, используемая для гигиены.",
    price: 158.0,
    images: [
      require("@/assets/products/papel-higinieco.png"),
      require("@/assets/products/papel-higinieco.png"),
      require("@/assets/products/papel-higinieco.png"),
    ],
    quantity: 10,
    unit: "10 рулонов",
    categories: ["Хиты продаж", "Бумага"],
    featured: true,
    store_id: 3,
  },
  {
    id: 7,
    name: "Белый лук",
    description: "Белый лук - это лук большого размера с сильным вкусом.",
    price: 39.5,
    images: [
      require("@/assets/products/cebolla-blanca.png"),
      require("@/assets/products/cebolla-blanca.png"),
      require("@/assets/products/cebolla-blanca.png"),
    ],
    quantity: 10,
    unit: "1 кг",
    categories: ["Хиты продаж", "Овощи и фрукты"],
    featured: true,
    store_id: 1,
  },
  {
    id: 8,
    name: "Морковь",
    description: "Морковь - это морковь большого размера со сладким вкусом.",
    price: 19.0,
    images: [
      require("@/assets/products/zanahoria.png"),
      require("@/assets/products/zanahoria.png"),
      require("@/assets/products/zanahoria.png"),
    ],
    quantity: 10,
    unit: "1 кг",
    categories: ["Хиты продаж", "Овощи и фрукты"],
    featured: true,
    store_id: 1,
  },
  {
    id: 9,
    name: "Лимон без косточек",
    description: "Лимон без косточек - это лимон большого размера с кислым вкусом.",
    price: 34.9,
    images: [
      require("@/assets/products/limon-sin-semilla.png"),
      require("@/assets/products/limon-sin-semilla.png"),
      require("@/assets/products/limon-sin-semilla.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Овощи и фрукты"],
    featured: true,
    store_id: 1,
  },
  {
    id: 10,
    name: "Филе тилапии",
    description: "Филе тилапии - это белое и нежное рыбное филе.",
    price: 122.9,
    images: [
      require("@/assets/products/filete-de-tilapia.png"),
      require("@/assets/products/filete-de-tilapia.png"),
      require("@/assets/products/filete-de-tilapia.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Морепродукты и растительные"],
    featured: true,
    store_id: 3,
  },
  {
    id: 11,
    name: "Pescado Sierra Madre",
    description: "Pescado Sierra Madre es un pescado de mar y sabor suave.",
    price: 186.4,
    images: [
      require("@/assets/products/pescado-sierra-madre.png"),
      require("@/assets/products/pescado-sierra-madre.png"),
      require("@/assets/products/pescado-sierra-madre.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Морепродукты и растительные"],
    featured: true,
    store_id: 3,
  },
  {
    id: 12,
    name: "Pescado Lenguado",
    description: "Pescado Lenguado es un pescado de mar y sabor suave.",
    price: 319.2,
    images: [
      require("@/assets/products/pescado-lenguado.png"),
      require("@/assets/products/pescado-lenguado.png"),
      require("@/assets/products/pescado-lenguado.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Морепродукты и растительные"],
    featured: true,
    store_id: 3,
  },
  {
    id: 13,
    name: "Codillo Chamorro",
    description: "Codillo Chamorro es un codillo de cerdo y sabor suave.",
    price: 77.0,
    images: [
      require("@/assets/products/codillo-chamorro.png"),
      require("@/assets/products/codillo-chamorro.png"),
      require("@/assets/products/codillo-chamorro.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Морепродукты и растительные"],
    featured: true,
    store_id: 3,
  },
  {
    id: 14,
    name: "Белые яйца",
    description: "Белые яйца - это куриные яйца с мягким вкусом.",
    price: 88.9,
    images: [
      require("@/assets/products/huevo-blanco.png"),
      require("@/assets/products/huevo-blanco.png"),
      require("@/assets/products/huevo-blanco.png"),
    ],
    quantity: 10,
    unit: "30 яиц",
    categories: ["Молочные продукты и яйца"],
    featured: true,
    store_id: 3,
  },
  {
    id: 15,
    name: "Молоко Прайм",
    description: "Молоко Прайм - это коровье молоко с мягким вкусом.",
    price: 25.9,
    images: [
      require("@/assets/products/leche-pronto.png"),
      require("@/assets/products/leche-pronto.png"),
      require("@/assets/products/leche-pronto.png"),
    ],
    quantity: 10,
    unit: "380 ml",
    categories: ["Молочные продукты и яйца"],
    featured: true,
    store_id: 3,
  },
  {
    id: 16,
    name: "Молоко Альпура",
    description: "Молоко Альпура - это коровье молоко с мягким вкусом.",
    price: 101.0,
    images: [
      require("@/assets/products/leche-alpura.png"),
      require("@/assets/products/leche-alpura.png"),
      require("@/assets/products/leche-alpura.png"),
    ],
    quantity: 10,
    unit: "1L c/u",
    categories: ["Молочные продукты и яйца"],
    featured: true,
    store_id: 3,
  },
  {
    id: 17,
    name: "Huevo San Juan",
    description: "Huevo San Juan es un huevo de gallina y sabor suave.",
    price: 39.0,
    images: [
      require("@/assets/products/huevo-san-juan.png"),
      require("@/assets/products/huevo-san-juan.png"),
      require("@/assets/products/huevo-san-juan.png"),
    ],
    quantity: 10,
    unit: "12 яиц",
    categories: ["Молочные продукты и яйца"],
    featured: true,
    store_id: 3,
  },
  {
    id: 18,
    name: "Leche Lala",
    description: "Leche Lala es una leche de vaca y sabor suave.",
    price: 144.0,
    images: [
      require("@/assets/products/leche-lala.png"),
      require("@/assets/products/leche-lala.png"),
      require("@/assets/products/leche-lala.png"),
    ],
    quantity: 10,
    unit: "1 L",
    categories: ["Молочные продукты и яйца"],
    featured: true,
    store_id: 3,
  },
  {
    id: 19,
    name: "Сливочный сыр",
    description: "Сливочный сыр - это коровий сыр с мягким вкусом.",
    price: 47.5,
    images: [
      require("@/assets/products/queso-crema.png"),
      require("@/assets/products/queso-crema.png"),
      require("@/assets/products/queso-crema.png"),
    ],
    quantity: 10,
    unit: "200 g",
    categories: ["Сыры"],
    featured: true,
    store_id: 3,
  },
  {
    id: 20,
    name: "Queso Rebanado",
    description: "Queso Rebanado es un queso de vaca y sabor suave.",
    price: 93.5,
    images: [
      require("@/assets/products/queso-rebanado-400g.png"),
      require("@/assets/products/queso-rebanado-400g.png"),
      require("@/assets/products/queso-rebanado-400g.png"),
    ],
    quantity: 10,
    unit: "400 g",
    categories: ["Сыры"],
    featured: true,
    store_id: 3,
  },
  {
    id: 21,
    name: "Queso Rebanado",
    description: "Queso Rebanado es un queso de vaca y sabor suave.",
    price: 53.0,
    images: [
      require("@/assets/products/queso-rebanado-200g.png"),
      require("@/assets/products/queso-rebanado-200g.png"),
      require("@/assets/products/queso-rebanado-200g.png"),
    ],
    quantity: 10,
    unit: "200 g",
    categories: ["Сыры"],
    featured: true,
    store_id: 3,
  },
  {
    id: 22,
    name: "Queso Panela",
    description: "Queso Panela es un queso de vaca y sabor suave.",
    price: 79.0,
    images: [
      require("@/assets/products/queso-panela.png"),
      require("@/assets/products/queso-panela.png"),
      require("@/assets/products/queso-panela.png"),
    ],
    quantity: 10,
    unit: "400 g",
    categories: ["Сыры"],
    featured: true,
    store_id: 3,
  },
  {
    id: 23,
    name: "Queso Crema Light",
    description: "Queso Crema Light es un queso de vaca y sabor suave.",
    price: 36.65,
    images: [
      require("@/assets/products/queso-crema-light.png"),
      require("@/assets/products/queso-crema-light.png"),
      require("@/assets/products/queso-crema-light.png"),
    ],
    quantity: 10,
    unit: "150 g",
    categories: ["Сыры"],
    featured: true,
    store_id: 3,
  },
  {
    id: 24,
    name: "Целая курица",
    description: "Целая курица с мягким вкусом.",
    price: 51.0,
    images: [
      require("@/assets/products/pollo-entero.png"),
      require("@/assets/products/pollo-entero.png"),
      require("@/assets/products/pollo-entero.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Птица"],
    featured: true,
    store_id: 3,
  },
  {
    id: 25,
    name: "Куриная грудка",
    description: "Куриная грудка с мягким вкусом.",
    price: 99.9,
    images: [
      require("@/assets/products/pechuga-de-pollo.png"),
      require("@/assets/products/pechuga-de-pollo.png"),
      require("@/assets/products/pechuga-de-pollo.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Птица"],
    featured: true,
    store_id: 3,
  },
  {
    id: 26,
    name: "Pechuga sin Hueso",
    description: "Pechuga sin Hueso es un pollo y sabor suave.",
    price: 154.0,
    images: [
      require("@/assets/products/pechuga-sin-hueso.png"),
      require("@/assets/products/pechuga-sin-hueso.png"),
      require("@/assets/products/pechuga-sin-hueso.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Птица"],
    featured: true,
    store_id: 3,
  },
  {
    id: 27,
    name: "Pierna y Muslo",
    description: "Pierna y Muslo es un pollo y sabor suave.",
    price: 44.9,
    images: [
      require("@/assets/products/pierna-y-muslo.png"),
      require("@/assets/products/pierna-y-muslo.png"),
      require("@/assets/products/pierna-y-muslo.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Птица"],
    featured: true,
    store_id: 3,
  },
  {
    id: 28,
    name: "Milanesa Pollo",
    description: "Milanesa Pollo es un pollo y sabor suave.",
    price: 174.0,
    images: [
      require("@/assets/products/milanesa-pollo.png"),
      require("@/assets/products/milanesa-pollo.png"),
      require("@/assets/products/milanesa-pollo.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Птица"],
    featured: true,
    store_id: 3,
  },
  {
    id: 29,
    name: "Индейка",
    description: "Индейка с мягким вкусом.",
    price: 59.0,
    images: [
      require("@/assets/products/jamon-de-pavo.png"),
      require("@/assets/products/jamon-de-pavo.png"),
      require("@/assets/products/jamon-de-pavo.png"),
    ],
    quantity: 10,
    unit: "450 g",
    categories: ["Колбасы и сосиски"],
    featured: true,
    store_id: 3,
  },
  {
    id: 30,
    name: "Pechuga de Pavo",
    description: "Pechuga de Pavo es un jamón y sabor suave.",
    price: 48.85,
    images: [
      require("@/assets/products/pechuga-de-pavo.png"),
      require("@/assets/products/pechuga-de-pavo.png"),
      require("@/assets/products/pechuga-de-pavo.png"),
    ],
    quantity: 10,
    unit: "250 g",
    categories: ["Колбасы и сосиски"],
    featured: true,
    store_id: 3,
  },
  {
    id: 31,
    name: "Jamón de Pierna",
    description: "Jamón de Pierna es un jamón y sabor suave.",
    price: 120.0,
    images: [
      require("@/assets/products/jamon-de-pierna.png"),
      require("@/assets/products/jamon-de-pierna.png"),
      require("@/assets/products/jamon-de-pierna.png"),
    ],
    quantity: 10,
    unit: "1 kg",
    categories: ["Колбасы и сосиски"],
    featured: true,
    store_id: 3,
  },
  {
    id: 32,
    name: "Salchicha Alpino",
    description: "Salchicha Alpino es un jamón y sabor suave.",
    price: 33.8,
    images: [
      require("@/assets/products/salchicha-alpino.png"),
      require("@/assets/products/salchicha-alpino.png"),
      require("@/assets/products/salchicha-alpino.png"),
    ],
    quantity: 10,
    unit: "500 g",
    categories: ["Колбасы и сосиски"],
    featured: true,
    store_id: 3,
  },
  {
    id: 33,
    name: "Tocino Fud Ahumado",
    description: "Tocino Fud Ahumado es un jamón y sabor suave.",
    price: 69.5,
    images: [
      require("@/assets/products/tocino-fud-ahumado.png"),
      require("@/assets/products/tocino-fud-ahumado.png"),
      require("@/assets/products/tocino-fud-ahumado.png"),
    ],
    quantity: 10,
    unit: "250 g",
    categories: ["Колбасы и сосиски"],
    featured: true,
    store_id: 3,
  },
];

export default { stores, categories, products };
